// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhamDangKhoa_W345_C2.Models;

#nullable disable

namespace PhamDangKhoa_W345_C2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520014812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhamDangKhoa_W345_C2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desktop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gaming Gear"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Linh kiện"
                        });
                });

            modelBuilder.Entity("PhamDangKhoa_W345_C2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Laptop HP Pavilion mỏng nhẹ, hiệu năng cao phù hợp cho sinh viên và dân văn phòng.",
                            ImageUrl = "/images/Hp1.png",
                            Name = "Laptop HP Pavilion",
                            Price = 15000000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Laptop doanh nhân Lenovo ThinkPad siêu bền bỉ, bàn phím gõ cực êm.",
                            ImageUrl = "/images/Lap1.png",
                            Name = "Laptop Lenovo ThinkPad",
                            Price = 25000000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Laptop gaming quốc dân Acer Nitro 5 với tản nhiệt cực tốt và cấu hình mạnh mẽ.",
                            ImageUrl = "/images/Nitro1.png",
                            Name = "Laptop Acer Nitro 5",
                            Price = 22000000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Laptop gaming cao cấp HP OMEN với thiết kế sang trọng, hiệu năng đỉnh cao.",
                            ImageUrl = "/images/OM1.png",
                            Name = "Laptop HP OMEN",
                            Price = 35000000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Laptop chuyên game Asus ROG mang lại trải nghiệm chơi game tuyệt vời.",
                            ImageUrl = "/images/80.jpg",
                            Name = "Laptop Asus ROG",
                            Price = 30000000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Laptop Dell XPS 15 với màn hình vô cực tuyệt đẹp, dành cho người dùng sáng tạo.",
                            ImageUrl = "/images/OIP.jpg",
                            Name = "Laptop Dell XPS 15",
                            Price = 40000000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Bộ PC Gaming Alpha với tản nhiệt nước, vỏ case trong suốt tuyệt đẹp.",
                            ImageUrl = "/images/PCA.jpg",
                            Name = "PC Gaming Alpha",
                            Price = 28000000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "PC chuyên dụng cho dân đồ họa 3D, dựng phim với bộ vi xử lý đa nhân siêu tốc.",
                            ImageUrl = "/images/PCB.jpg",
                            Name = "PC Đồ Họa Beta",
                            Price = 32000000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Máy tính để bàn cấu hình Core i5 nhỏ gọn, hoạt động êm ái thích hợp cho không gian làm việc.",
                            ImageUrl = "/images/PCA2.png",
                            Name = "PC Văn Phòng Core i5",
                            Price = 10000000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Máy trạm Workstation Xeon sức mạnh vượt trội cho mọi tác vụ nặng nhất.",
                            ImageUrl = "/images/PCB2.png",
                            Name = "PC Workstation Xeon",
                            Price = 45000000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Chuột chơi game không dây siêu nhẹ.",
                            ImageUrl = "https://picsum.photos/300/300?random=11",
                            Name = "Chuột Gaming Logitech",
                            Price = 1200000m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Bàn phím cơ cao cấp với đèn LED RGB.",
                            ImageUrl = "https://picsum.photos/300/300?random=12",
                            Name = "Bàn phím cơ Razer",
                            Price = 2500000m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Tai nghe chống ồn chủ động.",
                            ImageUrl = "https://picsum.photos/300/300?random=13",
                            Name = "Tai nghe Sony",
                            Price = 3000000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Màn hình 27 inch 4K IPS.",
                            ImageUrl = "https://picsum.photos/300/300?random=14",
                            Name = "Màn hình Dell UltraSharp",
                            Price = 8000000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Ổ cứng SSD NVMe tốc độ cao.",
                            ImageUrl = "https://picsum.photos/300/300?random=15",
                            Name = "Ổ cứng SSD Samsung 1TB",
                            Price = 2000000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "RAM DDR4 3200MHz.",
                            ImageUrl = "https://picsum.photos/300/300?random=16",
                            Name = "RAM Corsair 16GB",
                            Price = 1500000m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Card đồ họa chơi game tầm trung.",
                            ImageUrl = "https://picsum.photos/300/300?random=17",
                            Name = "Card đồ họa RTX 3060",
                            Price = 9000000m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Bo mạch chủ cao cấp cho Intel.",
                            ImageUrl = "https://picsum.photos/300/300?random=18",
                            Name = "Mainboard ASUS ROG",
                            Price = 4000000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Tản nhiệt AIO có màn hình LCD.",
                            ImageUrl = "https://picsum.photos/300/300?random=19",
                            Name = "Tản nhiệt nước NZXT",
                            Price = 3500000m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Nguồn máy tính chuẩn 80 Plus Gold.",
                            ImageUrl = "https://picsum.photos/300/300?random=20",
                            Name = "Nguồn Corsair 750W",
                            Price = 2200000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
