// <auto-generated />
using Bai6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bai6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bai6.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desktop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gaming Gear"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Linh kiện"
                        });
                });

            modelBuilder.Entity("Bai6.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Laptop HP Pavilion mỏng nhẹ, hiệu năng cao phù hợp cho sinh viên và dân văn phòng.",
                            ImageUrl = "/images/Hp1.png",
                            Name = "Laptop HP Pavilion",
                            Price = 15000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Laptop doanh nhân Lenovo ThinkPad siêu bền bỉ, bàn phím gõ cực êm.",
                            ImageUrl = "/images/Lap1.png",
                            Name = "Laptop Lenovo ThinkPad",
                            Price = 25000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Laptop gaming quốc dân Acer Nitro 5 với tản nhiệt cực tốt và cấu hình mạnh mẽ.",
                            ImageUrl = "/images/Nitro1.png",
                            Name = "Laptop Acer Nitro 5",
                            Price = 22000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Laptop gaming cao cấp HP OMEN với thiết kế sang trọng, hiệu năng đỉnh cao.",
                            ImageUrl = "/images/OM1.png",
                            Name = "Laptop HP OMEN",
                            Price = 35000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Laptop chuyên game Asus ROG mang lại trải nghiệm chơi game tuyệt vời.",
                            ImageUrl = "/images/asusrog.jpg",
                            Name = "Laptop Asus ROG",
                            Price = 30000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Laptop Dell XPS 15 với màn hình vô cực tuyệt đẹp, dành cho người dùng sáng tạo.",
                            ImageUrl = "/images/OIP.jpg",
                            Name = "Laptop Dell XPS 15",
                            Price = 40000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Bộ PC Gaming Alpha với tản nhiệt nước, vỏ case trong suốt tuyệt đẹp.",
                            ImageUrl = "/images/PCA.jpg",
                            Name = "PC Gaming Alpha",
                            Price = 28000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "PC chuyên dụng cho dân đồ họa 3D, dựng phim với bộ vi xử lý đa nhân siêu tốc.",
                            ImageUrl = "/images/PCB.jpg",
                            Name = "PC Đồ Họa Beta",
                            Price = 32000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Máy tính để bàn cấu hình Core i5 nhỏ gọn, hoạt động êm ái thích hợp cho không gian làm việc.",
                            ImageUrl = "/images/PCA2.png",
                            Name = "PC Văn Phòng Core i5",
                            Price = 10000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Máy trạm Workstation Xeon sức mạnh vượt trội cho mọi tác vụ nặng nhất.",
                            ImageUrl = "/images/PCB2.png",
                            Name = "PC Workstation Xeon",
                            Price = 45000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Chuột chơi game không dây siêu nhẹ.",
                            ImageUrl = "/images/Logi1.png",
                            Name = "Chuột Gaming Logitech",
                            Price = 1200000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Bàn phím cơ cao cấp với đèn LED RGB.",
                            ImageUrl = "/images/Razer.png",
                            Name = "Bàn phím cơ Razer",
                            Price = 2500000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Tai nghe chống ồn chủ động.",
                            ImageUrl = "/images/sony-headphone.jpg",
                            Name = "Tai nghe Sony",
                            Price = 3000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Màn hình 27 inch 4K IPS.",
                            ImageUrl = "/images/dell-ultrasharp.jpg",
                            Name = "Màn hình Dell UltraSharp",
                            Price = 8000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Ổ cứng SSD NVMe tốc độ cao.",
                            ImageUrl = "/images/samsung-ssd.jpg",
                            Name = "Ổ cứng SSD Samsung 1TB",
                            Price = 2000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "RAM DDR4 3200MHz.",
                            ImageUrl = "/images/corsair-ram.png",
                            Name = "RAM Corsair 16GB",
                            Price = 1500000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Card đồ họa chơi game tầm trung.",
                            ImageUrl = "/images/rtx3060.jpg",
                            Name = "Card đồ họa RTX 3060",
                            Price = 9000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Bo mạch chủ cao cấp cho Intel.",
                            ImageUrl = "/images/asus-rog-mainboard.jpg",
                            Name = "Mainboard ASUS ROG",
                            Price = 4000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Tản nhiệt AIO có màn hình LCD.",
                            ImageUrl = "/images/nzxt-aio.jpg",
                            Name = "Tản nhiệt nước NZXT",
                            Price = 3500000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Nguồn máy tính chuẩn 80 Plus Gold.",
                            ImageUrl = "/images/corsair-psu.jpg",
                            Name = "Nguồn Corsair 750W",
                            Price = 2200000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Laptop Apple với chip M2 siêu mạnh mẽ.",
                            ImageUrl = "/images/macbook-neo.jpg",
                            Name = "MacBook Pro M2",
                            Price = 35000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "Laptop siêu nhẹ chỉ 1.1kg, pin trâu.",
                            ImageUrl = "/images/Lap12.png",
                            Name = "Laptop LG Gram 16",
                            Price = 38000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Máy tính siêu nhỏ gọn phù hợp tivi phòng khách.",
                            ImageUrl = "/images/intel-nuc.jpg",
                            Name = "PC Mini Intel NUC",
                            Price = 12000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Máy trạm Apple hiệu năng đồ họa cực đỉnh.",
                            ImageUrl = "/images/mac-studio.jpg",
                            Name = "Mac Studio M2 Max",
                            Price = 55000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Tay cầm chơi game tốt nhất trên Windows.",
                            ImageUrl = "/images/xbox-controller.jpg",
                            Name = "Tay cầm Xbox Series X",
                            Price = 1500000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Webcam chuẩn Full HD cho streamer.",
                            ImageUrl = "/images/logitech-c920.jpg",
                            Name = "Webcam Logitech C920",
                            Price = 1800000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Loa di động âm thanh sống động.",
                            ImageUrl = "/images/jbl-speaker.jpg",
                            Name = "Loa Bluetooth JBL",
                            Price = 2000000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Description = "Ổ cứng lưu trữ dữ liệu dung lượng cao.",
                            ImageUrl = "/images/seagate-hdd.jpg",
                            Name = "Ổ cứng HDD Seagate 2TB",
                            Price = 1400000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Description = "Vỏ máy tính bằng thép với mặt kính cường lực.",
                            ImageUrl = "/images/nzxt-h510.jpg",
                            Name = "Vỏ Case NZXT H510",
                            Price = 1900000m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Description = "Quạt tản nhiệt siêu êm, lưu lượng gió lớn.",
                            ImageUrl = "/images/noctua-fan.jpg",
                            Name = "Quạt tản nhiệt Noctua",
                            Price = 800000m,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("Bai6.Models.Product", b =>
                {
                    b.HasOne("Bai6.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bai6.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
